[package]
name = "mobile-sdk"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
# FFI and serialization
cxx = { version = "1.0.160", features = ["alloc", "std", "c++20"] }
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Random number generation
rand = "0.8"

# Aleo cryptographic library with full features
snarkvm-console = { version = "4.2.0", default-features = false, features = ["account"] }

# Explicit vendored dependencies for cross-compilation
openssl-sys = { version = "0.9", features = ["vendored"] }
curl-sys = { version = "0.4", features = ["static-curl", "static-ssl"] }

[build-dependencies]
cxx-build = "1.0.160"

[lib]
name = "provable_mobile_sdk"
crate-type = ["cdylib", "staticlib"]
path = "src/rust/lib.rs"

[profile.release]
panic = "abort"