[package]
name = "mobile-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
# Provable SDK dependencies - use console with default features to get network types
snarkvm-console = "0.16"

# FFI and serialization
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Random number generation
rand = "0.8"

[lib]
name = "provable_mobile_sdk"
crate-type = ["cdylib", "staticlib"]
path = "src/rust/lib.rs"