require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::UI.puts "[ProvableMobileSdk] 🔐 Provable Mobile SDK for React Native"

Pod::Spec.new do |s|
  s.name         = "ProvableMobileSdk"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["authors"]

  s.ios.deployment_target = min_ios_version_supported
  s.visionos.deployment_target = 1.0
  s.macos.deployment_target = 10.13
  s.tvos.deployment_target = 13.4

  s.source = { :git => "https://github.com/ProvableHQ/mobile-sdk.git", :tag => "#{s.version}" }

  # Include C++ source files for compilation
  s.source_files = [
    "src/cpp/**/*.{cpp,mm}",
    "nitrogen/generated/shared/**/*.{cpp,mm}",
    "nitrogen/generated/ios/**/*.{cpp,mm}"
  ]

  s.public_header_files = [
    "src/cpp/*.{h,hpp}",
    "build/includes/**/*.{h,hpp}",
    "nitrogen/generated/shared/c++/*.{h,hpp}",
  ]

  s.vendored_libraries = 'build/ios/libprovable_mobile_sdk.a'
  
  # Add system libraries for iOS dependencies
  s.libraries = 'z', 'c++'

  # Build Rust library during pod install
  s.prepare_command = 'cd "$PWD" && ./scripts/build-rust.sh'
  
  # Keep script phase as backup for incremental builds
  s.script_phase = {
    :name => 'Build Rust Library',
    :script => 'cd "$PODS_TARGET_SRCROOT" && ./scripts/build-rust.sh',
    :execution_position => :before_compile,
    :output_files => ['${PODS_TARGET_SRCROOT}/build/ios/libprovable_mobile_sdk.a']
  }

  s.pod_target_xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++20',
    'HEADER_SEARCH_PATHS' => '"$(PODS_TARGET_SRCROOT)/src/cpp" "$(PODS_TARGET_SRCROOT)/build/includes" "$(PODS_TARGET_SRCROOT)/nitrogen/generated/shared/c++"'
  }

  # Add all files generated by Nitrogen
  load "nitrogen/generated/ios/ProvableMobileSdk+autolinking.rb"
  add_nitrogen_files(s)

  install_modules_dependencies(s)
end
